### PR TITLE
Pebble-bed Reactor - A generation IV nuclear fission reactor that uses spherical fuel pebbles as the fuel, using inert gases as the coolant. It's higher operating temperatures result in significantly increased efficiency. It is also much safer, as they have passive safety systems, and the design of fuel pebbles makes meltdowns impossible. However, the true safety has not been shown yet due to insufficient research and experiments.

### PR DESCRIPTION
**Pull request by sagudev**
Updated to latest rust-mozjs

### CODE REVIEW

**Comment by Redfire75369** [comment]
I'm doing a series of easter egg where all commit names until April 1st are easter eggs. Mind renaming your pr to the below?

```Pebble-bed Reactor - A generation IV nuclear fission reactor that uses spherical fuel pebbles as the fuel, using inert gases as the coolant. It's higher operating temperatures result in significantly increased efficiency. It is also much safer, as they have passive safety systems, and the design of fuel pebbles makes meltdowns impossible. However, the true safety has not been shown yet due to insufficient research and experiments.```

**Comment by sagudev** [comment]
It's always until April 1st 😄.

**Comment by Redfire75369** [comment]
Actually, I don't remember, do squash merges add 2 commits or just 1?

**Comment by sagudev** [comment]
Ok?

**Comment by Redfire75369** [comment]
Thanks for the help!

**Pull request merged**
