### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by sagudev**
replace `#[apply(js_fn!)]` with `#[js_fn]`

### CODE REVIEW

**Comment by sagudev** [comment]
`#[js_fn]` is jut wrapper for `js_fn_m!` macro

**Comment by Redfire75369** [comment]
Since this means that the `macro_rules_attribute` crate is no longer required, can you remove that from the dependencies and remove the their externs.

**Comment by sagudev** [comment]
Of course it would be better to impl js_fn directly as proc macro but this will do for now.

**Comment by sagudev** [comment]
@Redfire75369 ready for merge!

**Review by Redfire75369 — APPROVED** [review]

**Pull request merged**
